### Listar bebidas
GET http://localhost:5000/bebidas

### listar plato fuerte
GET http://localhost:5000/platoFuerte

### listar aperitivos
GET http://localhost:5000/aperitivos

### listar postres
GET http://localhost:5000/postres

### Listar menu
GET http://localhost:5000

### Crear platillo
POST http://localhost:5000/
Content-Type: application/json

{
    "nombre": "vinito",
    "precio": "9000",
    "categoria": "hey",
    "descripcion": "Arroz con el delicioso sabor de casa acompañado de los de los precios mas accesibles y bla bla blaaaaaa",
    "imagen": "URL_DUMMY" 
}

### Actualizar platilo
PUT http://localhost:5000/608b67e2e786d338d8d43801
Content-Type: application/json

{
    "precio": "1800 por docena"
}

### Eliminar platillo
DELETE http://localhost:5000/608b67e2e786d338d8d43801